// /lib/intel/constants.ts

export const PARTICIPATION_THRESHOLDS = {
  LOW: 25,
  WEAK: 50,
  HEALTHY: 70,
  STRONG: 100,
};

export const VOLATILITY_THRESHOLDS = {
  LOW: 2,
  NORMAL: 5,
  HIGH: 8,
};

export const BTC_DOMINANCE_THRESHOLDS = {
  STRONG: 55,
  EXTREME: 62,
};

export const MARKET_REGIMES = {
  RISK_ON: "RISK_ON",
  RISK_OFF: "RISK_OFF",
  ROTATION: "ROTATION",
  CHOPPY: "CHOPPY",
  ACCUMULATION: "ACCUMULATION",
  DISTRIBUTION: "DISTRIBUTION",
  RECOVERY: "RECOVERY",
  BREAKOUT: "BREAKOUT",
};

export const MOMENTUM_STATES = {
  ACCELERATING: "ACCELERATING",
  STABILIZING: "STABILIZING",
  DECELERATING: "DECELERATING",
  REVERSING: "REVERSING",
  NEUTRAL: "NEUTRAL",
};

export const TRANSITION_STATES = {
  RECOVERY: "RECOVERY",
  BREAKDOWN: "BREAKDOWN",
  STABILIZING: "STABILIZING",
  EXPANSION: "EXPANSION",
  DISTRIBUTION: "DISTRIBUTION",
  ACCUMULATION: "ACCUMULATION",
};